# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from typing import List, Optional, Union
from uuid import UUID

from fastapi import Path

from .models import (
    Courier,
    CreateCourierResponse,
    CreateOrderResponse,
    Error,
    Location,
    NewCourier,
    NewOrder,
    Order,
)
