# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import List, Optional, Union
from uuid import UUID

from fastapi import APIRouter, Path

from .models import (
    Courier,
    CreateCourierResponse,
    CreateOrderResponse,
    Error,
    Location,
    NewCourier,
    NewOrder,
    Order,
)
from .routers import (
    complete_order,
    create_courier,
    create_order,
    get_couriers,
    get_orders,
    move_courier,
)

router = APIRouter()

router.include_router(complete_order.router)
router.include_router(create_courier.router)
router.include_router(create_order.router)
router.include_router(get_couriers.router)
router.include_router(get_orders.router)
router.include_router(move_courier.router)
