# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field, conint, constr


class Address(BaseModel):
    country: str = Field(..., description='Страна')
    city: str = Field(..., description='Город')
    street: str = Field(..., description='Улица')
    house: str = Field(..., description='Дом')
    apartment: str = Field(..., description='Квартира')


class Location(BaseModel):
    x: conint(ge=0) = Field(..., description='X')
    y: conint(ge=0) = Field(..., description='Y')


class NewOrder(BaseModel):
    id: UUID = Field(..., description='Идентификатор')
    address: Address = Field(..., description='Адрес')
    volume: Optional[conint(ge=0)] = Field(None, description='Объем')


class Order(BaseModel):
    id: UUID = Field(..., description='Идентификатор')
    location: Location = Field(..., description='Геолокация')


class NewCourier(BaseModel):
    name: constr(min_length=1) = Field(..., description='Имя')


class Courier(BaseModel):
    id: UUID = Field(..., description='Идентификатор')
    name: str = Field(..., description='Имя')
    location: Location = Field(..., description='Геолокация')


class CreateOrderResponse(BaseModel):
    orderId: UUID


class CreateCourierResponse(BaseModel):
    courierId: UUID


class Error(BaseModel):
    code: int = Field(..., description='Код ошибки')
    message: str = Field(..., description='Текст ошибки')
