# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import List, Optional, Union
from uuid import UUID

from fastapi import APIRouter, Path

from .models import (
    Courier,
    CreateCourierResponse,
    CreateOrderResponse,
    Error,
    Location,
    NewCourier,
    NewOrder,
    Order,
)

router = APIRouter(tags=['CompleteOrder'])


@router.post(
    '/api/v1/couriers/{courierId}/orders/{orderId}/complete',
    response_model=None,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['CompleteOrder'],
)
def complete_order(
    courier_id: UUID = Path(..., alias='courierId'),
    order_id: UUID = Path(..., alias='orderId'),
) -> Optional[Error]:
    """
    Завершить заказ
    """
    pass
