# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from decimal import Decimal

from fastapi import APIRouter, Depends
from that_depends import inject

from src.core.application.commands.create_order import CreateOrderCommand
from src.core.application.commands.create_order import create_order as create_order_use_case
from src.core.domain.model.address import Address
from src.core.domain.model.volume import Volume
from src.core.domain.ports import UnitOfWork
from src.di.container import Container

from ..models import (
    CreateOrderResponse,
    Error,
    NewOrder,
)

router = APIRouter(tags=['CreateOrder'])


@router.post(
    '/api/v1/orders',
    response_model=CreateOrderResponse,
    status_code=201,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['CreateOrder'],
)
@inject
async def create_order(body: NewOrder, uow: UnitOfWork = Depends(Container.unit_of_work)) -> CreateOrderResponse:
    """
    Создать заказ
    """
    address = Address(
        country=body.address.country,
        city=body.address.city,
        street=body.address.street,
        house=body.address.house,
        apartment=body.address.apartment,
    )
    volume_value = Decimal(str(body.volume)) if body.volume is not None else Decimal("1")
    volume = Volume(_value=volume_value)

    cmd = CreateOrderCommand(
        order_id=body.id,
        address=address,
        volume=volume,
    )
    await create_order_use_case(cmd, uow)

    return CreateOrderResponse(orderId=body.id)
