# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import List, Optional, Union
from uuid import UUID

from fastapi import APIRouter, Path

from .models import (
    Courier,
    CreateCourierResponse,
    CreateOrderResponse,
    Error,
    Location,
    NewCourier,
    NewOrder,
    Order,
)

router = APIRouter(tags=['CreateCourier'])


@router.post(
    '/api/v1/couriers',
    response_model=CreateCourierResponse,
    status_code=201,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['CreateCourier'],
)
def create_courier(body: NewCourier) -> Union[CreateCourierResponse, Error]:
    """
    Добавить курьера
    """
    pass
