# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import List, Optional, Union
from uuid import UUID

from fastapi import APIRouter, Path

from .models import (
    Courier,
    CreateCourierResponse,
    CreateOrderResponse,
    Error,
    Location,
    NewCourier,
    NewOrder,
    Order,
)

router = APIRouter(tags=['CreateOrder'])


@router.post(
    '/api/v1/orders',
    response_model=CreateOrderResponse,
    status_code=201,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['CreateOrder'],
)
def create_order(body: NewOrder) -> Union[CreateOrderResponse, Error]:
    """
    Создать заказ
    """
    pass
