# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import List, Union

from fastapi import APIRouter
from that_depends import inject

from src.core.application.queries.get_not_completed_orders import get_not_completed_orders as get_not_completed_orders_use_case
from src.core.domain.ports import UnitOfWork
from src.di.container import container

from ..models import (
    Error,
    Location,
    Order,
)

router = APIRouter(tags=['GetOrders'])


@router.get(
    '/api/v1/orders/active',
    response_model=List[Order],
    responses={'400': {'model': Error}, '500': {'model': Error}},
    tags=['GetOrders'],
)
@inject
async def get_orders(uow: UnitOfWork = container.unit_of_work) -> List[Order]:
    """
    Получить все незавершенные заказы
    """
    dtos = await get_not_completed_orders_use_case(uow)

    return [
        Order(
            id=dto.id,
            location=Location(x=dto.location.x, y=dto.location.y),
        )
        for dto in dtos
    ]
