# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from fastapi import APIRouter, Depends
from that_depends import inject

from src.core.application.queries.get_all_couriers import get_all_couriers as get_all_couriers_use_case
from src.core.domain.ports import UnitOfWork
from src.di.container import Container

from ..models import (
    Courier,
    Error,
    Location,
)

router = APIRouter(tags=['GetCouriers'])


@router.get(
    '/api/v1/couriers',
    response_model=list[Courier],
    responses={'400': {'model': Error}, '500': {'model': Error}},
    tags=['GetCouriers'],
)
@inject
async def get_couriers(uow: UnitOfWork = Depends(Container.unit_of_work)) -> list[Courier]:
    """
    Получить всех курьеров
    """
    dtos = await get_all_couriers_use_case(uow)

    return [
        Courier(
            id=dto.id,
            name=dto.name,
            location=Location(x=dto.location.x, y=dto.location.y),
        )
        for dto in dtos
    ]
