# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import List, Optional, Union
from uuid import UUID

from fastapi import APIRouter, Path

from .models import (
    Courier,
    CreateCourierResponse,
    CreateOrderResponse,
    Error,
    Location,
    NewCourier,
    NewOrder,
    Order,
)

router = APIRouter(tags=['GetCouriers'])


@router.get(
    '/api/v1/couriers',
    response_model=List[Courier],
    responses={'400': {'model': Error}, '500': {'model': Error}},
    tags=['GetCouriers'],
)
def get_couriers() -> Union[List[Courier], Error]:
    """
    Получить всех курьеров
    """
    pass
