# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import List, Optional, Union
from uuid import UUID

from fastapi import APIRouter, Path

from .models import (
    Courier,
    CreateCourierResponse,
    CreateOrderResponse,
    Error,
    Location,
    NewCourier,
    NewOrder,
    Order,
)

router = APIRouter(tags=['GetOrders'])


@router.get(
    '/api/v1/orders/active',
    response_model=List[Order],
    responses={'400': {'model': Error}, '500': {'model': Error}},
    tags=['GetOrders'],
)
def get_orders() -> Union[List[Order], Error]:
    """
    Получить все незавершенные заказы
    """
    pass
