# generated by fastapi-codegen:
#   filename:  openapi_contract.yaml

from __future__ import annotations

from typing import List, Optional, Union
from uuid import UUID

from fastapi import APIRouter, Path

from .models import (
    Courier,
    CreateCourierResponse,
    CreateOrderResponse,
    Error,
    Location,
    NewCourier,
    NewOrder,
    Order,
)

router = APIRouter(tags=['MoveCourier'])


@router.post(
    '/api/v1/couriers/{courierId}/move',
    response_model=None,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['MoveCourier'],
)
def move_courier(
    courier_id: UUID = Path(..., alias='courierId'), body: Location = ...
) -> Optional[Error]:
    """
    Переместить курьера
    """
    pass
