"""Initial tables

Revision ID: 07721d8b464e
Revises: 
Create Date: 2026-06-27 21:18:19.623027

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '07721d8b464e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_x', sa.Integer(), nullable=False),
    sa.Column('location_y', sa.Integer(), nullable=False),
    sa.Column('max_volume', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_x', sa.Integer(), nullable=False),
    sa.Column('location_y', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('courier_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('location_x', sa.Integer(), nullable=False),
    sa.Column('location_y', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('orders')
    op.drop_table('couriers')
    # ### end Alembic commands ###
